### ISSUE TITLE
Crash when having only one item

### ISSUE THREAD

**Issue by johntyty912** [mars885/value-picker#1]
Hi, the app crash when only one items,
I think it would be better if the valuePicker can still display if there is only one item

**Comment by mars885** [comment]
Hello.

It is [desired behavior](https://github.com/mars885/value-picker/blob/master/value-picker/src/main/java/com/paulrybitskyi/valuepicker/ValuePickerView.kt#L242) to throw an exception when the list contains less than 1 item. The core idea of the ValuePickerView is to be able to pick a value from a set of options, meaning there has to be at least two options that a user must pick between.

Hope it helps.

**Comment by barchinsky** [comment]
It would be much nicer from API-wise to let developer to decide if it is fine or not. In some use cases to keep UX experience on high level it is still needed to display one item instead of doing checks and provide custom behaviour. Is there any technical reasons to introduce this limitation?

**Comment by mars885** [comment]
After thinking about it for some time, I've reached a conclusion that it does make sense to support having only one item as well. I've released a new version called [1.0.2](https://github.com/mars885/value-picker/releases/tag/v1.0.2) that supports this now. Please check it out and let me know if you have any problems.
