### ISSUE TITLE
Add gif instead of Yt link

### ISSUE THREAD

**Issue by prateekcode** [mars885/value-picker#3]
Hey, It will be great if you add .gif  instead of a Youtube link as a demo in the documentation, so anyone can easily get the whole point.

**Comment by mars885** [comment]
I disagree. The length of the video is 1 minute and 16 seconds. A GIF file with a length like that will have enormous size, probably worse quality, and there will be no way to rewind to a particular part.

**Comment by prateekcode** [comment]
Yes, you're right!
